# 🌈 Culture Protocol Engine Docker Compose
version: '3.8'

services:
  culture-protocol:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      # Mount for development (uncomment for dev mode)
      # - .:/app
      - culture_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add database if needed
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: culture_protocol
  #     POSTGRES_USER: culture
  #     POSTGRES_PASSWORD: protocol
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  culture_data:
  # postgres_data:
  # redis_data:

networks:
  default:
    name: culture-protocol-network